name: dart_zero_endpoint
description: Minimal Dart backend that serves a 0kb endpoint
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.12.0
dependencies:
  async: ^2.13.1
  convert: ^3.1.2
  http: ^1.6.0
  mysql1: ^0.20.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
